<?php session_start();?>
<!DOCTYPE html>
<html lang="en">
<div id="page">
	
	<?php include("./header.html"); ?>
	<head>
		<!--css-->
			<!--page-specific-->
			<link rel="stylesheet" href="./css/side-nav.css">
			<link rel="stylesheet" href="./css/charts.css">
		<!--scripts-->
			<!--page-specific-->
				<!--js-->
				<!--php-->
				<?php include("./assets/fusioncharts.php"); ?>
				<?php include("./charts/query.php"); ?>

	</head>
	
	<body>
		<div class="container-1" id="page-elements">
	<!-- main navigation-->
				<?php include("./main-nav.html"); ?>
				<!-- sidebar navigation-->
				<!--create sidebar-top-->
					<div class="row sidebar-top">
						<p id="sidebar-top-text">CHARTS</p>
					</div>
				
	<!--sidebar tabs-->
			<!--content-->
			<div class="content">
				<div class="container-2" id="page-content">
			
					<!--Tabs-->
							<div class="tab-menu sidebar-nav col-2">
								<div class="btn-block btn-mine btn-group-vertical sidebar btn-mine" data-toggle="buttons" type="radio" id="sidebar" role="tablist">
									<a href="#deck-type_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="deck-type_link"><img src="../assets/icons/deck.png" class="sidebar-icon" alt="Deck Type" id="deck-type_img"></a>
									<a href="#faction_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="faction_link"><img src="../assets/icons/faction.png" class="sidebar-icon" alt="Faction" id="faction_img"></a>
									<a href="#influence_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="influence_link"><img src="../assets/icons/influence.png" class="sidebar-icon" alt="Influence" id="influence_img"></a>
									<a href="#card-type_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="card-type_link"><img src="../assets/icons/cardtype.png" class="sidebar-icon" alt="Card Type" id="card-type_img"></a>
									<a href="#individual_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="individual_link"><img src="../assets/icons/individual.png" class="sidebar-icon" alt="Individual Cards" id="individual_img"></a>
									<a href="#power_pane" class="list-group-item btn-mine"  data-toggle="tab" role="tab" id="power_link"><img src="../assets/icons/power.png" class="sidebar-icon" alt="Power" id="power_img"></a>
									<a href="#gameplay_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="gameplay_link"><img src="../assets/icons/gameplay.png" class="sidebar-icon" alt="Game Play" id="gameplay_img"></a>
									<a href="#reference_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="reference_link"><img src="../assets/icons/reference.png" class="sidebar-icon" alt="Reference" id="reference_img"></a>
								</div>
							</div><!--end tab menu-->
							
					<div class="tab-content">
						<!-- Charts - Deck Type-->
						<div class="tab-pane active" id="deck-type_pane">
							<div class="container" id="deck-type">
								<div class="row">
									<div id="deck-type_container" class="container">
										<h3><strong>Deck Type</strong>: </h3> <h4>Statistics in this category include all cards which might be played in a given deck type.</h4>
										<h4>E.g. Mono Fire includes only Fire cards, while Rakano includes Mono Fire, Mono Justice, and dual-color Rakano cards.</h4>
										<hr>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryDeckGeneral">
														<a data-toggle="collapse" href="#deckGeneral" aria-expanded="true">GENERAL OVERVIEW<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckGeneral" class="collapse" role="tabpanel">
																<!-- Card Availability -->
																<div id="deckTotalCards" class="line_graph chart" alt="Card Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckTotalCardsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckTotalCardsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br> Power cards excluded from count.
																							<br> Nictotraxian excluded from count.
																							<br> Transmuted Monuments included in count.
																							<br> Faction "None" includes all tokens generated by other cards.
																							<br> All variable-cost cards without a minimum value are encoded as "X" cost.  Former Powersurge cards are not included in "X".
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckTotalCardsData" aria-expanded="true">Raw data<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckTotalCardsData" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>	
																							<?php if (count($_SESSION['deckTotalCardsData']) > 0): ?>		<table class="sorttable datatable">
																										<thead>
																												<?php 
																													for($i = 0; $i < count($_SESSION['deckTotalCardsData']); $i++) {
																														echo '<tr>';
																														echo '<td>'.($_SESSION['labels1'][$i]).'</td>';
																														$arr1 = $_SESSION['deckTotalCardsData'][$i];
																														for($j = 0; $j < count($arr1); $j++) {
																															$arr2 = array_values($arr1[$j]);
																															for($k = 0; $k < count($arr2); $k++) {
																																echo '<td>'.$arr2[$k].'</td>';
																																if ($k==14) echo '</tr>';
																																};
																															};
																														};
																													 ?>
																										</thead>
																									</table>
																								<?php endif; ?>
																						</BLOCKQUOTE>
																					</div>
																			</div>
																<hr>
																
																<!-- Avg Influence -->									
																<div id="deckInfluence" class="line_graph chart" alt="Average Influence Cost by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckInfluenceInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckInfluenceInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Averages taken for total influence cost.  I.e. All influences on a card summed, then selected for some critera.  The selected sums were themselves averaged.
																							<br>Tokens counted as "None" for influence cost.
																							<br>Transmuted Monuments included in count.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																			
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryDeckRemoval">
														<a data-toggle="collapse" href="#deckRemoval" aria-expanded="true">REMOVAL<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckRemoval" class="collapse" role="tabpanel">
																<!-- Removal -->
																<div id="deckRemoval" class="line_graph chart" alt="Removal Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckRemovalInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckRemovalInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Removal:
																							<br>	- Deadly
																							<br>	- Deal Damage
																							<br>	- Discard
																							<br>	- Exhaust
																							<br>	- Kill
																							<br>	- Killer
																							<br>	- Negate
																							<br>	- Sacrifice
																							<br>	- Scare
																							<br>	- Silence
																							<br>	- Slow*
																							<br>	- Steal*
																							<br>	- Stun
																							<br>	- Transform
																							<br>	- Teleport*
																							<br>	- ALL numeric debuffs
																							<br>*These card types had variable text or no keyword, and were searched by text regex.  You may see the full document used to populate this column at <a href="https://github.com/kaelosthereckoning/site/blob/master/MySQLUpdates/cards_removal">Github</a>.
																							<br>All cards, whether unit, spell, or attachment, were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>														
																<hr>
																
																<!-- Debuffs -->
																<div id="deckDebuff" class="line_graph chart" alt="Stat-Debuff Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckDebuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																							<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Forced Discard -->
																<div id="deckMill" class="line_graph chart" alt="Forced Discard Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckMillInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckMillInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Forced Discard:
																							<br>	- All "Discard" targeting opponent deck or hand.
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Reactive -->
																<div id="deckReactive" class="line_graph chart" alt="Reactive Card Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckReactiveInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckReactiveInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Reactive:
																							<br>	- Ambush
																							<br>	- Fast Spell
																							<br>
																							<br>All spells and units were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>				
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryDeckBuffVDebuff">
														<a data-toggle="collapse" href="#deckBuffVDebuff" aria-expanded="true">BUFFS V. DEBUFFS<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckBuffVDebuff" class="collapse" role="tabpanel">										
																<!-- Buff -->
																<div id="deckBuff" class="line_graph chart" alt="Stat-Buff Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckBuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckBuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: +X/+X, +Armor, +Strength, or +Health.
																							<br>Variable buffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>		
										
																<!-- Debuffs -->
																<div id="deckDebuff" class="line_graph chart" alt="Stat-Debuff Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckDebuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																							<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryDeckSpellsCurses">
														<a data-toggle="collapse" href="#deckSpellsCurses" aria-expanded="true">SPELLS AND CURSES<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckSpellsCurses" class="collapse" role="tabpanel">
																<!-- Spells -->
																<div id="deckSpells" class="line_graph chart" alt="Spell Availability by Deck Type"></div>	
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckSpellsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckSpellsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Units with Spell effects not included.
																							<br>Curses not included, as they are attachments.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Curses -->
																<div id="deckCurses" class="line_graph chart" alt="Curse Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckCursesInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Curses, but not Cursed Relics, included.
																							<br>Spells not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryDeckUnitOD">
														<a data-toggle="collapse" href="#deckUnitOD" aria-expanded="true">UNITS: Offense and Defense<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckUnitOD" class="collapse" role="tabpanel">
																<!-- Units -->
																<div id="deckUnits" class="line_graph chart" alt="Unit Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckUnitsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckUnitsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no faction not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Unit Offense -->
																<div id="deckOffense" class="line_graph chart" alt="Unit Strength by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckOffenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckOffenseInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no faction not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Unit Defense -->
																<div id="deckDefense" class="line_graph chart" alt="Unit Health by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckDefenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckDefenseInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no faction not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryDeckAllAttachments">
														<a data-toggle="collapse" href="#deckAllAttachments" aria-expanded="true">ATTACHMENTS<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckAllAttachments" class="collapse" role="tabpanel">
																<!-- Attachments -->
																<div id="deckAttachments" class="line_graph chart" alt="Attachment Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckAttachmentsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckAttachmentsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all Curses, Cursed Relics, Relics, Relic Weapons, and Weapons.
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>Transmuted Monuments included in count.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Weapons -->
																<div id="deckWeapons" class="line_graph chart" alt="Weapon Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckWeaponsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Only unit-based weapons included.
																							<br>Transmuted Monuments included.
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>Relic Weapons not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																<!-- Relic Weapons -->
																<div id="deckRelicWeapons" class="line_graph chart" alt="Relic Weapon Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckRelicWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckRelicWeaponsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>			

																			
																<hr>
																<!-- Relics -->
																<div id="deckRelics" class="line_graph chart" alt="Relic Availability by Deck Type"></div>	
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckRelicsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Relic Weapons not included.
																							<br>However, Relics generating armor or health are included. (e.g. Stronghold's Visage)
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Cursed Relics -->
																<div id="deckCursedRelics" class="line_graph chart" alt="Cursed Relic Availability by Deck Type"></div>										
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckCursedRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckCursedRelicsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Neither Relics nor Curses included, only Cursed Relics.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Curses -->
																<div id="deckCurses" class="line_graph chart" alt="Curse Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckCursesInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Curses, but not Cursed Relics, included.
																							<br>Spells not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryDeckCycling">
														<a data-toggle="collapse" href="#deckCycling" aria-expanded="true">CARD CYCLING<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckCycling" class="collapse" role="tabpanel">
																<!-- Card Cycling -->
																<div id="deckCycle" class="line_graph chart" alt="Card Cycling Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckCycleInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckCycleInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Card Cycling:
																							<br>	- Draw
																							<br>	- Shuffle
																							<br>	- Deck Return
																							<br>	- Discard
																							<br>	- Forced Discard
																							<br>	- Warp
																							<br>	- Revenge
																							<br>
																							<br>All spells and units were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Card Draw -->
																<div id="deckDraw" class="line_graph chart" alt="Card Draw Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckDrawInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckDrawInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Draw:
																							<br>	- Anything with "Draw" keyword ("Quickdraw" and other non-draw cards filtered out.)
																							<br>	- Cards with "Warp" keyword.
																							<br>
																							<br>All spells and units were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Deck Manipulation -->
																<div id="deckManipulate" class="line_graph chart" alt="Deck Manipulation Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckManipulateInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckManipulateInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Deck Manipulation:
																							<br>	- Return card to deck
																							<br>	- Reorder deck (i.e. "place on bottom" / "place on top")
																							<br>	- View top card and optionally reorder
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Discard -->
																<div id="deckDiscard" class="line_graph chart" alt="Discard Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckDiscardInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckDiscardInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Discard:
																							<br>	- Self-targeted discard
																							<br>	- Opponent-targeted ("forced") discard
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Forced Discard -->
																<div id="deckMill" class="line_graph chart" alt="Forced Discard Availability by Deck Type"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#deckMillInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="deckMillInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Forced Discard:
																							<br>	- All "Discard" targeting opponent deck or hand.
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>
										<div id="" class="" alt=""></div>
									</div><!--close deck-type_container-->
								</div><!--close row-->
							</div><!--close deck-type-->
						</div><!--close pane-->
						
						<!-- Charts - Faction-->
						<div class="tab-pane" id="faction_pane">
							<div class="container" id="faction">
								<div class="row">
									<div id="faction_container" class="container">
										<h3><strong>Faction</strong>: </h3> <h4>Statistics in this category allow each card to fit into precisely one faction based on its per-card influence types.</h4>
										<h4>E.g. Mono Fire includes only cards with only Fire influence, while Rakano includes only dual-color Fire/Justice cards.</h4>
										<hr>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryFactionGeneral">
														<a data-toggle="collapse" href="#factionGeneral" aria-expanded="true">GENERAL OVERVIEW<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionGeneral" class="collapse" role="tabpanel">
																<!-- Card Availability -->
																<div id="factionTotalCards" class="line_graph chart" alt="Card Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionTotalCardsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionTotalCardsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br> Power cards excluded from count.
																							<br> Nictotraxian excluded from count.
																							<br> Transmuted Monuments included in count.
																							<br> Faction "None" includes all tokens generated by other cards.
																							<br> All variable-cost cards without a minimum value are encoded as "X" cost.  Former Powersurge cards are not included in "X".
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionTotalCardsData" aria-expanded="true">Raw data<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionTotalCardsData" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>	
																							<?php if (count($_SESSION['factionTotalCardsData']) > 0): ?>		<table class="sorttable datatable">
																										<thead>
																												<?php 
																													for($i = 0; $i < count($_SESSION['factionTotalCardsData']); $i++) {
																														echo '<tr>';
																														echo '<td>'.($_SESSION['labels1'][$i]).'</td>';
																														$arr1 = $_SESSION['factionTotalCardsData'][$i];
																														for($j = 0; $j < count($arr1); $j++) {
																															$arr2 = array_values($arr1[$j]);
																															for($k = 0; $k < count($arr2); $k++) {
																																echo '<td>'.$arr2[$k].'</td>';
																																if ($k==14) echo '</tr>';
																																};
																															};
																														};
																													 ?>
																										</thead>
																									</table>
																								<?php endif; ?>
																						</BLOCKQUOTE>
																					</div>
																			</div>
																<hr>
																
																<!-- Avg Influence -->									
																<div id="factionInfluence" class="line_graph chart" alt="Average Influence Cost by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionInfluenceInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionInfluenceInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Averages taken for total influence cost.  I.e. All influences on a card summed, then selected for some critera.  The selected sums were themselves averaged.
																							<br>Tokens counted as "None" for influence cost.
																							<br>Transmuted Monuments included in count.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																			
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryFactionRemoval">
														<a data-toggle="collapse" href="#factionRemoval" aria-expanded="true">REMOVAL<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionRemoval" class="collapse" role="tabpanel">
																<!-- Removal -->
																<div id="factionRemoval" class="line_graph chart" alt="Removal Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionRemovalInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionRemovalInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Removal:
																							<br>	- Deadly
																							<br>	- Deal Damage
																							<br>	- Discard
																							<br>	- Exhaust
																							<br>	- Kill
																							<br>	- Killer
																							<br>	- Negate
																							<br>	- Sacrifice
																							<br>	- Scare
																							<br>	- Silence
																							<br>	- Slow*
																							<br>	- Steal*
																							<br>	- Stun
																							<br>	- Transform
																							<br>	- Teleport*
																							<br>	- ALL numeric debuffs
																							<br>*These card types had variable text or no keyword, and were searched by text regex.  You may see the full document used to populate this column at <a href="https://github.com/kaelosthereckoning/site/blob/master/MySQLUpdates/cards_removal">Github</a>.
																							<br>All cards, whether unit, spell, or attachment, were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>														
																<hr>
																
																<!-- Debuffs -->
																<div id="factionDebuff" class="line_graph chart" alt="Stat-Debuff Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionDebuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																							<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Forced Discard -->
																<div id="factionMill" class="line_graph chart" alt="Forced Discard Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionMillInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionMillInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Forced Discard:
																							<br>	- All "Discard" targeting opponent deck or hand.
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Reactive -->
																<div id="factionReactive" class="line_graph chart" alt="Reactive Card Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionReactiveInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionReactiveInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Reactive:
																							<br>	- Ambush
																							<br>	- Fast Spell
																							<br>
																							<br>All spells and units were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>				
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryFactionBuffVDebuff">
														<a data-toggle="collapse" href="#factionBuffVDebuff" aria-expanded="true">BUFFS V. DEBUFFS<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionBuffVDebuff" class="collapse" role="tabpanel">										
																<!-- Buff -->
																<div id="factionBuff" class="line_graph chart" alt="Stat-Buff Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionBuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionBuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: +X/+X, +Armor, +Strength, or +Health.
																							<br>Variable buffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>		
										
																<!-- Debuffs -->
																<div id="factionDebuff" class="line_graph chart" alt="Stat-Debuff Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionDebuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																							<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryFactionSpellsCurses">
														<a data-toggle="collapse" href="#factionSpellsCurses" aria-expanded="true">SPELLS AND CURSES<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionSpellsCurses" class="collapse" role="tabpanel">
																<!-- Spells -->
																<div id="factionSpells" class="line_graph chart" alt="Spell Availability by Faction"></div>	
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionSpellsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionSpellsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Units with Spell effects not included.
																							<br>Curses not included, as they are attachments.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Curses -->
																<div id="factionCurses" class="line_graph chart" alt="Curse Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionCursesInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Curses, but not Cursed Relics, included.
																							<br>Spells not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryFactionUnitOD">
														<a data-toggle="collapse" href="#factionUnitOD" aria-expanded="true">UNITS: Offense and Defense<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionUnitOD" class="collapse" role="tabpanel">
																<!-- Units -->
																<div id="factionUnits" class="line_graph chart" alt="Unit Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionUnitsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionUnitsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no faction not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Unit Offense -->
																<div id="factionOffense" class="line_graph chart" alt="Unit Strength by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionOffenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionOffenseInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no faction not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Unit Defense -->
																<div id="factionDefense" class="line_graph chart" alt="Unit Health by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionDefenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionDefenseInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no faction not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryFactionAllAttachments">
														<a data-toggle="collapse" href="#factionAllAttachments" aria-expanded="true">ATTACHMENTS<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionAllAttachments" class="collapse" role="tabpanel">
																<!-- Attachments -->
																<div id="factionAttachments" class="line_graph chart" alt="Attachment Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionAttachmentsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionAttachmentsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all Curses, Cursed Relics, Relics, Relic Weapons, and Weapons.
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>Transmuted Monuments included in count.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Weapons -->
																<div id="factionWeapons" class="line_graph chart" alt="Weapon Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionWeaponsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Only unit-based weapons included.
																							<br>Transmuted Monuments included.
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>Relic Weapons not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																<!-- Relic Weapons -->
																<div id="factionRelicWeapons" class="line_graph chart" alt="Relic Weapon Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionRelicWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionRelicWeaponsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>			

																			
																<hr>
																<!-- Relics -->
																<div id="factionRelics" class="line_graph chart" alt="Relic Availability by Faction"></div>	
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionRelicsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Relic Weapons not included.
																							<br>However, Relics generating armor or health are included. (e.g. Stronghold's Visage)
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Cursed Relics -->
																<div id="factionCursedRelics" class="line_graph chart" alt="Cursed Relic Availability by Faction"></div>										
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionCursedRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionCursedRelicsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Neither Relics nor Curses included, only Cursed Relics.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Curses -->
																<div id="factionCurses" class="line_graph chart" alt="Curse Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionCursesInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Curses, but not Cursed Relics, included.
																							<br>Spells not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryFactionCycling">
														<a data-toggle="collapse" href="#factionCycling" aria-expanded="true">CARD CYCLING<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionCycling" class="collapse" role="tabpanel">
																<!-- Card Cycling -->
																<div id="factionCycle" class="line_graph chart" alt="Card Cycling Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionCycleInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionCycleInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Card Cycling:
																							<br>	- Draw
																							<br>	- Shuffle
																							<br>	- Deck Return
																							<br>	- Discard
																							<br>	- Forced Discard
																							<br>	- Warp
																							<br>	- Revenge
																							<br>
																							<br>All spells and units were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Card Draw -->
																<div id="factionDraw" class="line_graph chart" alt="Card Draw Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionDrawInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionDrawInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Draw:
																							<br>	- Anything with "Draw" keyword ("Quickdraw" and other non-draw cards filtered out.)
																							<br>	- Cards with "Warp" keyword.
																							<br>
																							<br>All spells and units were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Deck Manipulation -->
																<div id="factionManipulate" class="line_graph chart" alt="Deck Manipulation Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionManipulateInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionManipulateInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Deck Manipulation:
																							<br>	- Return card to deck
																							<br>	- Reorder deck (i.e. "place on bottom" / "place on top")
																							<br>	- View top card and optionally reorder
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Discard -->
																<div id="factionDiscard" class="line_graph chart" alt="Discard Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionDiscardInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionDiscardInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Discard:
																							<br>	- Self-targeted discard
																							<br>	- Opponent-targeted ("forced") discard
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Forced Discard -->
																<div id="factionMill" class="line_graph chart" alt="Forced Discard Availability by Faction"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#factionMillInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="factionMillInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Forced Discard:
																							<br>	- All "Discard" targeting opponent deck or hand.
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>
										<div id="" class="" alt=""></div>
									</div><!--close faction_container-->
								</div><!--close row-->
							</div><!--close faction-->
						</div><!--close pane-->
						
						<!-- Charts - Influence -->
						<div class="tab-pane" id="influence_pane">
							<div class="container" id="influence">
								<div class="row">
									<div id="influence_container" class="container">
										<h3><strong>Influence</strong>: </h3> <h4>Statistics in this category include every card with a given Influence requirement, as a means of broadly characterizing each Influence.</h4>
										<h4>E.g. Fire includes every single card with any Fire Influence required (Fire + Rakano + Skycrag + Stonescar + Praxis).</h4>
										<hr>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryInfluenceGeneral">
														<a data-toggle="collapse" href="#influenceGeneral" aria-expanded="true">GENERAL OVERVIEW<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceGeneral" class="collapse" role="tabpanel">
																<!-- Card Availability -->
																<div id="influenceTotalCards" class="line_graph chart" alt="Card Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceTotalCardsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceTotalCardsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br> Power cards excluded from count.
																							<br> Nictotraxian excluded from count.
																							<br> Transmuted Monuments included in count.
																							<br> Influence "None" includes all tokens generated by other cards.
																							<br> All variable-cost cards without a minimum value are encoded as "X" cost.  Former Powersurge cards are not included in "X".
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceTotalCardsData" aria-expanded="true">Raw data<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceTotalCardsData" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>	
																							<?php if (count($_SESSION['influenceTotalCardsData']) > 0): ?>		<table class="sorttable datatable">
																										<thead>
																												<?php 
																													for($i = 0; $i < count($_SESSION['influenceTotalCardsData']); $i++) {
																														echo '<tr>';
																														echo '<td>'.($_SESSION['labels1'][$i]).'</td>';
																														$arr1 = $_SESSION['influenceTotalCardsData'][$i];
																														for($j = 0; $j < count($arr1); $j++) {
																															$arr2 = array_values($arr1[$j]);
																															for($k = 0; $k < count($arr2); $k++) {
																																echo '<td>'.$arr2[$k].'</td>';
																																if ($k==14) echo '</tr>';
																																};
																															};
																														};
																													 ?>
																										</thead>
																									</table>
																								<?php endif; ?>
																						</BLOCKQUOTE>
																					</div>
																			</div>
																<hr>
																
																<!-- Avg Influence -->									
																<div id="influenceInfluence" class="line_graph chart" alt="Average Influence Cost by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceInfluenceInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceInfluenceInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Averages taken for total influence cost.  I.e. All influences on a card summed, then selected for some critera.  The selected sums were themselves averaged.
																							<br>Tokens counted as "None" for influence cost.
																							<br>Transmuted Monuments included in count.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																			
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryInfluenceRemoval">
														<a data-toggle="collapse" href="#influenceRemoval" aria-expanded="true">REMOVAL<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceRemoval" class="collapse" role="tabpanel">
																<!-- Removal -->
																<div id="influenceRemoval" class="line_graph chart" alt="Removal Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceRemovalInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceRemovalInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Removal:
																							<br>	- Deadly
																							<br>	- Deal Damage
																							<br>	- Discard
																							<br>	- Exhaust
																							<br>	- Kill
																							<br>	- Killer
																							<br>	- Negate
																							<br>	- Sacrifice
																							<br>	- Scare
																							<br>	- Silence
																							<br>	- Slow*
																							<br>	- Steal*
																							<br>	- Stun
																							<br>	- Transform
																							<br>	- Teleport*
																							<br>	- ALL numeric debuffs
																							<br>*These card types had variable text or no keyword, and were searched by text regex.  You may see the full document used to populate this column at <a href="https://github.com/kaelosthereckoning/site/blob/master/MySQLUpdates/cards_removal">Github</a>.
																							<br>All cards, whether unit, spell, or attachment, were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>														
																<hr>
																
																<!-- Debuffs -->
																<div id="influenceDebuff" class="line_graph chart" alt="Stat-Debuff Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceDebuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																							<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Forced Discard -->
																<div id="influenceMill" class="line_graph chart" alt="Forced Discard Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceMillInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceMillInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Forced Discard:
																							<br>	- All "Discard" targeting opponent deck or hand.
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Reactive -->
																<div id="influenceReactive" class="line_graph chart" alt="Reactive Card Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceReactiveInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceReactiveInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Reactive:
																							<br>	- Ambush
																							<br>	- Fast Spell
																							<br>
																							<br>All spells and units were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>				
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryInfluenceBuffVDebuff">
														<a data-toggle="collapse" href="#influenceBuffVDebuff" aria-expanded="true">BUFFS V. DEBUFFS<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceBuffVDebuff" class="collapse" role="tabpanel">										
																<!-- Buff -->
																<div id="influenceBuff" class="line_graph chart" alt="Stat-Buff Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceBuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceBuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: +X/+X, +Armor, +Strength, or +Health.
																							<br>Variable buffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>		
										
																<!-- Debuffs -->
																<div id="influenceDebuff" class="line_graph chart" alt="Stat-Debuff Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceDebuffInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all spells, units, and attachments.
																							<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																							<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryInfluenceSpellsCurses">
														<a data-toggle="collapse" href="#influenceSpellsCurses" aria-expanded="true">SPELLS AND CURSES<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceSpellsCurses" class="collapse" role="tabpanel">
																<!-- Spells -->
																<div id="influenceSpells" class="line_graph chart" alt="Spell Availability by Influence"></div>	
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceSpellsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceSpellsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Units with Spell effects not included.
																							<br>Curses not included, as they are attachments.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Curses -->
																<div id="influenceCurses" class="line_graph chart" alt="Curse Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceCursesInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Curses, but not Cursed Relics, included.
																							<br>Spells not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryInfluenceUnitOD">
														<a data-toggle="collapse" href="#influenceUnitOD" aria-expanded="true">UNITS: Offense and Defense<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceUnitOD" class="collapse" role="tabpanel">
																<!-- Units -->
																<div id="influenceUnits" class="line_graph chart" alt="Unit Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceUnitsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceUnitsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no influence not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Unit Offense -->
																<div id="influenceOffense" class="line_graph chart" alt="Unit Strength by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceOffenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceOffenseInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no influence not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																
																<!-- Unit Defense -->
																<div id="influenceDefense" class="line_graph chart" alt="Unit Health by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceDefenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceDefenseInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Tokens and units with no influence not counted.
																							<br>Transmuted units counted.
																							<br>Spells producing units not counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryInfluenceAllAttachments">
														<a data-toggle="collapse" href="#influenceAllAttachments" aria-expanded="true">ATTACHMENTS<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceAllAttachments" class="collapse" role="tabpanel">
																<!-- Attachments -->
																<div id="influenceAttachments" class="line_graph chart" alt="Attachment Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceAttachmentsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceAttachmentsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Includes all Curses, Cursed Relics, Relics, Relic Weapons, and Weapons.
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>Transmuted Monuments included in count.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Weapons -->
																<div id="influenceWeapons" class="line_graph chart" alt="Weapon Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceWeaponsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Only unit-based weapons included.
																							<br>Transmuted Monuments included.
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>Relic Weapons not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
																<!-- Relic Weapons -->
																<div id="influenceRelicWeapons" class="line_graph chart" alt="Relic Weapon Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceRelicWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceRelicWeaponsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Spells producing weapons (e.g. Hone) not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>			

																			
																<hr>
																<!-- Relics -->
																<div id="influenceRelics" class="line_graph chart" alt="Relic Availability by Influence"></div>	
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceRelicsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Relic Weapons not included.
																							<br>However, Relics generating armor or health are included. (e.g. Stronghold's Visage)
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Cursed Relics -->
																<div id="influenceCursedRelics" class="line_graph chart" alt="Cursed Relic Availability by Influence"></div>										
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceCursedRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceCursedRelicsInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Neither Relics nor Curses included, only Cursed Relics.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																<!-- Curses -->
																<div id="influenceCurses" class="line_graph chart" alt="Curse Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceCursesInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Curses, but not Cursed Relics, included.
																							<br>Spells not included.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>																				
																<hr>
															</div>
														</div>
										<br><div role="tablist" aria-multiselectable="true" class="bigcat" id="categoryInfluenceCycling">
														<a data-toggle="collapse" href="#influenceCycling" aria-expanded="true">CARD CYCLING<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceCycling" class="collapse" role="tabpanel">
																<!-- Card Cycling -->
																<div id="influenceCycle" class="line_graph chart" alt="Card Cycling Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceCycleInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceCycleInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Card Cycling:
																							<br>	- Draw
																							<br>	- Shuffle
																							<br>	- Deck Return
																							<br>	- Discard
																							<br>	- Forced Discard
																							<br>	- Warp
																							<br>	- Revenge
																							<br>
																							<br>All spells and units were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Card Draw -->
																<div id="influenceDraw" class="line_graph chart" alt="Card Draw Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceDrawInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceDrawInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Draw:
																							<br>	- Anything with "Draw" keyword ("Quickdraw" and other non-draw cards filtered out.)
																							<br>	- Cards with "Warp" keyword.
																							<br>
																							<br>All spells and units were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Deck Manipulation -->
																<div id="influenceManipulate" class="line_graph chart" alt="Deck Manipulation Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceManipulateInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceManipulateInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Deck Manipulation:
																							<br>	- Return card to deck
																							<br>	- Reorder deck (i.e. "place on bottom" / "place on top")
																							<br>	- View top card and optionally reorder
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Discard -->
																<div id="influenceDiscard" class="line_graph chart" alt="Discard Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceDiscardInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceDiscardInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Discard:
																							<br>	- Self-targeted discard
																							<br>	- Opponent-targeted ("forced") discard
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>Cards with both "Discard" and "Draw" keywords are represented on both "Discard" and "Draw" graphs; however, each card will only be counted once on the overall "Card Cycling" graph.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
																
																<!-- Forced Discard -->
																<div id="influenceMill" class="line_graph chart" alt="Forced Discard Availability by Influence"></div>
																			<br><div role="tablist" aria-multiselectable="true">
																				<a data-toggle="collapse" href="#influenceMillInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
																					<div id="influenceMillInfo" class="collapse" role="tabpanel">
																						<BLOCKQUOTE>
																							<br>Card types represented as Forced Discard:
																							<br>	- All "Discard" targeting opponent deck or hand.
																							<br>
																							<br>All spells, units, and attachments were counted.
																							<br>
																							<br> Last update: October 30, 2017
																						</BLOCKQUOTE>
																					</div>
																			</div>										
																<hr>
															</div>
														</div>
										<div id="" class="" alt=""></div>
									</div><!--close influence_container-->
								</div><!--close row-->
							</div><!--close influence-->
						</div><!--close pane-->
					</div><!--end tab-content-->
				</div><!--end container-2-->
			</div><!--end content-->
				
	<!--footer-->
			<?php include("./footer.html"); ?>
			

		</div><!--end container-1-->
	</body>

	<!--post-load scripts-->
			<!--js-->
			<script>
				$('.collapse').on('shown.bs.collapse', function(){
					$(this).parent().find(".glyphicon-plus").removeClass("glyphicon-plus").addClass("glyphicon-minus");
				}).on('hidden.bs.collapse', function(){
					$(this).parent().find(".glyphicon-minus").removeClass("glyphicon-minus").addClass("glyphicon-plus");
				});
			</script>
			
			<!--php-->
			<?php
				session_unset(); 
				session_destroy(); 
			?>
			
</div> <!--end page-->
</html>
