<?php session_start();?>
<!DOCTYPE html>
<html lang="en">
<div id="page">
	
	<?php include("./header.html"); ?>
	<head>
		<!--css-->
			<!--page-specific-->
			<link rel="stylesheet" href="./css/side-nav.css">
			<link rel="stylesheet" href="./css/charts.css">
		<!--scripts-->
			<!--page-specific-->
				<!--js-->
				<!--php-->
				<?php include("./assets/fusioncharts.php"); ?>
				<?php include("./charts/query.php"); ?>

	</head>
	
	<body>
		<div class="container-1" id="page-elements">
	<!-- main navigation-->
				<?php include("./main-nav.html"); ?>
				<!-- sidebar navigation-->
				<!--create sidebar-top-->
					<div class="row sidebar-top">
						<p id="sidebar-top-text">CHARTS</p>
					</div>
				
	<!--sidebar tabs-->
			<!--content-->
			<div class="content">
				<div class="container-2" id="page-content">
			
					<!--Tabs-->
							<div class="tab-menu sidebar-nav col-2">
								<div class="btn-block btn-mine btn-group-vertical sidebar btn-mine" data-toggle="buttons" type="radio" id="sidebar" role="tablist">
									<a href="#deck-type_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="deck-type_link"><img src="../assets/icons/deck.png" class="sidebar-icon" alt="Deck Type" id="deck-type_img"></a>
									<a href="#faction_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="faction_link"><img src="../assets/icons/faction.png" class="sidebar-icon" alt="Faction" id="faction_img"></a>
									<a href="#influence_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="influence_link"><img src="../assets/icons/influence.png" class="sidebar-icon" alt="Influence" id="influence_img"></a>
									<a href="#card-type_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="card-type_link"><img src="../assets/icons/cardtype.png" class="sidebar-icon" alt="Card Type" id="card-type_img"></a>
									<a href="#individual_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="individual_link"><img src="../assets/icons/individual.png" class="sidebar-icon" alt="Individual Cards" id="individual_img"></a>
									<a href="#power_pane" class="list-group-item btn-mine"  data-toggle="tab" role="tab" id="power_link"><img src="../assets/icons/power.png" class="sidebar-icon" alt="Power" id="power_img"></a>
									<a href="#gameplay_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="gameplay_link"><img src="../assets/icons/gameplay.png" class="sidebar-icon" alt="Game Play" id="gameplay_img"></a>
									<a href="#reference_pane" class="list-group-item btn-mine" data-toggle="tab" role="tab" id="reference_link"><img src="../assets/icons/reference.png" class="sidebar-icon" alt="Reference" id="reference_img"></a>
								</div>
							</div><!--end tab menu-->
							
					<div class="tab-content">
						<!-- Charts - Deck Type-->
						<div class="tab-pane active" id="deck-type_pane">
							<div class="container" id="deck-type">
								<div class="row">
									<div id="deck-type_container" class="container">
										<h3><strong>Deck Type</strong>: </h3> <h4>Statistics in this category include all cards which might be played in a given deck type.</h4>
										<h4>E.g. Mono Fire includes only Fire cards, while Rakano includes Mono Fire, Mono Justice, and dual-color Rakano cards.</h4>
										<hr>
										<!-- Card Availability -->
										<div id="deckTotalCards" class="line_graph chart" alt="Card Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckTotalCardsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckTotalCardsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br> Power cards excluded from count.
																	<br> Nictotraxian excluded from count.
																	<br> Transmuted Monuments included in count.
																	<br> Faction "None" includes all tokens generated by other cards.
																	<br> All variable-cost cards without a minimum value are encoded as "X" cost.  Former Powersurge cards are not included in "X".
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckTotalCardsData" aria-expanded="true">Raw data<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckTotalCardsData" class="collapse" role="tabpanel">
																<BLOCKQUOTE>	
																	<?php if (count($_SESSION['deckTotalCardsData']) > 0): ?>		<table class="sorttable datatable">
																				<thead>
																						<?php 
																							for($i = 0; $i < count($_SESSION['deckTotalCardsData']); $i++) {
																								echo '<tr>';
																								echo '<td>'.($_SESSION['labels1'][$i]).'</td>';
																								$arr1 = $_SESSION['deckTotalCardsData'][$i];
																								for($j = 0; $j < count($arr1); $j++) {
																									$arr2 = array_values($arr1[$j]);
																									for($k = 0; $k < count($arr2); $k++) {
																										echo '<td>'.$arr2[$k].'</td>';
																										if ($k==14) echo '</tr>';
																										};
																									};
																								};
																							 ?>
																				</thead>
																			</table>
																		<?php endif; ?>
																</BLOCKQUOTE>
															</div>
													</div>
										<hr>
										
										<!-- Avg Influence -->									
										<div id="deckInfluence" class="line_graph chart" alt="Average Influence Cost by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckInfluenceInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckInfluenceInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Averages taken for total influence cost.  I.e. All influences on a card summed, then selected for some critera.  The selected sums were themselves averaged.
																	<br>Tokens counted as "None" for influence cost.
																	<br>Transmuted Monuments included in count.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Removal -->
										<div id="deckRemoval" class="line_graph chart" alt="Removal Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckRemovalInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckRemovalInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Removal:
																	<br>	- Deadly
																	<br>	- Deal Damage
																	<br>	- Discard
																	<br>	- Exhaust
																	<br>	- Kill
																	<br>	- Killer
																	<br>	- Negate
																	<br>	- Sacrifice
																	<br>	- Scare
																	<br>	- Silence
																	<br>	- Slow*
																	<br>	- Steal*
																	<br>	- Stun
																	<br>	- Transform
																	<br>	- Teleport*
																	<br>	- ALL numeric debuffs
																	<br>*These card types had variable text or no keyword, and were searched by text regex.  You may see the full document used to populate this column at <a href="https://github.com/kaelosthereckoning/site/blob/master/MySQLUpdates/cards_removal">Github</a>.
																	<br>All cards, whether unit, spell, or attachment, were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>														
										<hr>
										
										<!-- Debuffs -->
										<div id="deckDebuffs" class="line_graph chart" alt="Stat-Debuffs by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckDebuffInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all spells, units, and attachments.
																	<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																	<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Buffs -->
										<div id="deckBuffs" class="line_graph chart" alt="Stat-Buff Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckBuffsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckBuffsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all spells, units, and attachments.
																	<br>Debuffs must have been in one of four formats: +X/-X, +Armor, +Strength, or +Health.
																	<br>Variable buffs were included as long as they had some real, numeric value at time of cast / play.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>										
										
										<!-- Reactive -->
										<div id="deckReactive" class="line_graph chart" alt="Reactive Card Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckReactiveInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckReactiveInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Reactive:
																	<br>	- Ambush
																	<br>	- Fast Spell
																	<br>
																	<br>All spells and units were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Card Cycling -->
										<div id="deckCardCycling" class="line_graph chart" alt="Card Cycling Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckCyclingInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckCyclingInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Card Cycling:
																	<br>	- Draw
																	<br>	- Discard
																	<br>
																	<br>All spells and units were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Deck Manipulation -->
										<div id="deckManipulation" class="line_graph chart" alt="Deck Manipulation Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckManipulationInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckManipulationInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Deck Manipulation:
																	<br>	- Search for and draw card
																	<br>	- Return card to deck
																	<br>	- Reorder deck
																	<br>	- Create cards & shuffle into deck
																	<br>	- Buffs applied to deck (in part or total)
																	<br>	- View top card
																	<br>	- Transform, silence, or slow cards in opponent deck
																	<br>	- Add cards to opponent deck
																	<br>	- Take cards from opponent deck
																	<br>	- All draw and discard effects
																	<br>
																	<br>All spells, units, and attachments were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Units -->
										<div id="deckUnits" class="line_graph chart" alt="Unit Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckUnitsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckUnitsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no faction not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Unit Offense -->
										<div id="deckOffense" class="line_graph chart" alt="Unit Strength by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckOffenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckOffenseInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no faction not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Unit Defense -->
										<div id="deckDefense" class="line_graph chart" alt="Unit Health by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckDefenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckDefenseInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no faction not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Spells -->
										<div id="deckSpells" class="line_graph chart" alt="Spell Availability by Deck Type"></div>	
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckSpellsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckSpellsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Units with Spell effects not included.
																	<br>Curses not included, as they are attachments.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Curses -->
										<div id="deckCurses" class="line_graph chart" alt="Curse Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckCursesInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Curses, but not Cursed Relics, included.
																	<br>Spells not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										<!-- Weapons -->
										<div id="deckWeapons" class="line_graph chart" alt="Weapon Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckWeaponsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Only unit-based weapons included.
																	<br>Transmuted Monuments included.
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>Relic Weapons not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										<!-- Relic Weapons -->
										<div id="deckRelicWeapons" class="line_graph chart" alt="Relic Weapon Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckRelicWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckRelicWeaponsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>			

													
										<hr>
										<!-- Relics -->
										<div id="deckRelics" class="line_graph chart" alt="Relic Availability by Deck Type"></div>	
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckRelicsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Relic Weapons not included.
																	<br>However, Relics generating armor or health are included. (e.g. Stronghold's Visage)
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<!-- Cursed Relics -->
										<div id="deckCursedRelics" class="line_graph chart" alt="Cursed Relic Availability by Deck Type"></div>										
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckCursedRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckCursedRelicsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Neither Relics nor Curses included, only Cursed Relics.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<!-- Attachments -->
										<div id="deckAttachments" class="line_graph chart" alt="Attachment Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckAttachmentsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckAttachmentsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all Curses, Cursed Relics, Relics, Relic Weapons, and Weapons.
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>Transmuted Monuments included in count.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										
										
										<!-- Attachments -->
										<div id="deckAttachments" class="line_graph chart" alt="Attachment Availability by Deck Type"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#deckAttachmentsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="deckAttachmentsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all Curses, Cursed Relics, Relics, Relic Weapons, and Weapons.
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>Transmuted Monuments included in count.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<div id="" class="" alt=""></div>
									</div><!--close deck-type_container-->
								</div><!--close row-->
							</div><!--close deck-type-->
						</div><!--close pane-->
						
						<!-- Charts - Faction-->
						<div class="tab-pane" id="faction_pane">
							<div class="container" id="faction">
								<div class="row">
									<div id="faction_container" class="container">
										<h3><strong>Faction</strong>: </h3> <h4>Statistics in this category allow each card to fit into precisely one faction based on its per-card influence types.</h4>
										<h4>E.g. Mono Fire includes only cards with only Fire influence, while Rakano includes only dual-color Fire/Justice cards.</h4>
										<hr>
										<!-- Card Availability -->
										<div id="factionTotalCards" class="line_graph chart" alt="Card Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionTotalCardsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionTotalCardsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br> Power cards excluded from count.
																	<br> Nictotraxian excluded from count.
																	<br> Transmuted Monuments included in count.
																	<br> Faction "None" includes all tokens generated by other cards.
																	<br> All variable-cost cards without a minimum value are encoded as "X" cost.  Former Powersurge cards are not included in "X".
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>
										<hr>
										
										<!-- Avg Influence -->									
										<div id="factionInfluence" class="line_graph chart" alt="Average Influence Cost by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionInfluenceInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionInfluenceInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Averages taken for total influence cost.  I.e. All influences on a card summed, then selected for some critera.  The selected sums were themselves averaged.
																	<br>Tokens counted as "None" for influence cost.
																	<br>Transmuted Monuments included in count.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Removal -->
										<div id="factionRemoval" class="line_graph chart" alt="Removal Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionRemovalInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionRemovalInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Removal:
																	<br>	- Deadly
																	<br>	- Deal Damage
																	<br>	- Discard
																	<br>	- Exhaust
																	<br>	- Kill
																	<br>	- Killer
																	<br>	- Negate
																	<br>	- Sacrifice
																	<br>	- Scare
																	<br>	- Silence
																	<br>	- Slow*
																	<br>	- Steal*
																	<br>	- Stun
																	<br>	- Transform
																	<br>	- Teleport*
																	<br>	- ALL numeric debuffs
																	<br>*These card types had variable text or no keyword, and were searched by text regex.  You may see the full document used to populate this column at <a href="https://github.com/kaelosthereckoning/site/blob/master/MySQLUpdates/cards_removal">Github</a>.
																	<br>All cards, whether unit, spell, or attachment, were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>														
										<hr>
										
										<!-- Debuffs -->
										<div id="factionDebuffs" class="line_graph chart" alt="Stat-Debuffs by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionDebuffInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all spells, units, and attachments.
																	<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																	<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Buffs -->
										<div id="factionBuffs" class="line_graph chart" alt="Stat-Buff Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionBuffsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionBuffsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all spells, units, and attachments.
																	<br>Debuffs must have been in one of four formats: +X/-X, +Armor, +Strength, or +Health.
																	<br>Variable buffs were included as long as they had some real, numeric value at time of cast / play.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>										
										
										<!-- Reactive -->
										<div id="factionReactive" class="line_graph chart" alt="Reactive Card Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionReactiveInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionReactiveInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Reactive:
																	<br>	- Ambush
																	<br>	- Fast Spell
																	<br>
																	<br>All spells and units were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<!-- Card Cycling -->
										<div id="factionCardCycling" class="line_graph chart" alt="Card Cycling Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionCyclingInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionCyclingInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Card Cycling:
																	<br>	- Draw
																	<br>	- Discard
																	<br>
																	<br>All spells and units were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Deck Manipulation -->
										<div id="factionManipulation" class="line_graph chart" alt="Deck Manipulation Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionManipulationInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionManipulationInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Deck Manipulation:
																	<br>	- Search for and draw card
																	<br>	- Return card to deck
																	<br>	- Reorder deck
																	<br>	- Create cards & shuffle into deck
																	<br>	- Buffs applied to deck (in part or total)
																	<br>	- View top card
																	<br>	- Transform, silence, or slow cards in opponent deck
																	<br>	- Add cards to opponent deck
																	<br>	- Take cards from opponent deck
																	<br>	- All draw and discard effects
																	<br>
																	<br>All spells, units, and attachments were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Units -->
										<div id="factionUnits" class="line_graph chart" alt="Unit Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionUnitsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionUnitsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no faction not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Unit Offense -->
										<div id="factionOffense" class="line_graph chart" alt="Unit Strength by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceOffenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceOffenseInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no faction not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Unit Defense -->
										<div id="factionDefense" class="line_graph chart" alt="Unit Health by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceDefenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceDefenseInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no faction not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Spells -->
										<div id="factionSpells" class="line_graph chart" alt="Spell Availability by Faction"></div>	
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionSpellsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionSpellsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Units with Spell effects not included.
																	<br>Curses not included, as they are attachments.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										<!-- Curses -->
										<div id="factionCurses" class="line_graph chart" alt="Curse Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionCursesInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Curses, but not Cursed Relics, included.
																	<br>Spells not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										<!-- Weapons -->
										<div id="factionWeapons" class="line_graph chart" alt="Weapon Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionWeaponsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Only unit-based weapons included.
																	<br>Transmuted Monuments included.
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>Relic Weapons not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										<!-- Relic Weapons -->
										<div id="factionRelicWeapons" class="line_graph chart" alt="Relic Weapon Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionRelicWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionRelicWeaponsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>			

													
										<hr>
										<!-- Relics -->
										<div id="factionRelics" class="line_graph chart" alt="Relic Availability by Faction"></div>	
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionRelicsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Relic Weapons not included.
																	<br>However, Relics generating armor or health are included. (e.g. Stronghold's Visage)
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<!-- Cursed Relics -->
										<div id="factionCursedRelics" class="line_graph chart" alt="Cursed Relic Availability by Faction"></div>										
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionCursedRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionCursedRelicsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Neither Relics nor Curses included, only Cursed Relics.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<!-- Attachments -->
										<div id="factionAttachments" class="line_graph chart" alt="Attachment Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#factionAttachmentsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="factionAttachmentsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all Curses, Cursed Relics, Relics, Relic Weapons, and Weapons.
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>Transmuted Monuments included in count.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<div id="" class="" alt=""></div>
									</div><!--close faction_container-->
								</div><!--close row-->
							</div><!--close faction-->
						</div><!--close pane-->
						
						<!-- Charts - Influence -->
						<div class="tab-pane" id="influence_pane">
							<div class="container" id="influence">
								<div class="row">
									<div id="influence_container" class="container">
										<h3><strong>Influence</strong>: </h3> <h4>Statistics in this category include every card with a given Influence requirement, as a means of broadly characterizing each Influence.</h4>
										<h4>E.g. Fire includes every single card with any Fire Influence required (Fire + Rakano + Skycrag + Stonescar + Praxis).</h4>
										<hr>
										
										<!-- Card Availability -->
										<div id="influenceTotalCards" class="line_graph chart" alt="Card Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceTotalCardsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceTotalCardsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br> Power cards excluded from count.
																	<br> Nictotraxian excluded from count.
																	<br> Transmuted Monuments included in count.
																	<br> Influence "None" includes all tokens generated by other cards.
																	<br> All variable-cost cards without a minimum value are encoded as "X" cost.  Former Powersurge cards are not included in "X".
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>
										<hr>
										
										<!-- Avg Influence -->									
										<div id="influenceInfluence" class="line_graph chart" alt="Average Influence Cost by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceInfluenceInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceInfluenceInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Averages taken for total influence cost.  I.e. All influences on a card summed, then selected for some critera.  The selected sums were themselves averaged.
																	<br>Tokens counted as "None" for influence cost.
																	<br>Transmuted Monuments included in count.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Removal -->
										<div id="influenceRemoval" class="line_graph chart" alt="Removal Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceRemovalInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceRemovalInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Removal:
																	<br>	- Deadly
																	<br>	- Deal Damage
																	<br>	- Discard
																	<br>	- Exhaust
																	<br>	- Kill
																	<br>	- Killer
																	<br>	- Negate
																	<br>	- Sacrifice
																	<br>	- Scare
																	<br>	- Silence
																	<br>	- Slow*
																	<br>	- Steal*
																	<br>	- Stun
																	<br>	- Transform
																	<br>	- Teleport*
																	<br>	- ALL numeric debuffs
																	<br>*These card types had variable text or no keyword, and were searched by text regex.  You may see the full document used to populate this column at <a href="https://github.com/kaelosthereckoning/site/blob/master/MySQLUpdates/cards_removal">Github</a>.
																	<br>All cards, whether unit, spell, or attachment, were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>														
										<hr>
										
										<!-- Debuffs -->
										<div id="influenceDebuffs" class="line_graph chart" alt="Stat-Debuffs by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceDebuffInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceDebuffInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all spells, units, and attachments.
																	<br>Debuffs must have been in one of four formats: -X/-X, -Armor, -Strength, or -Health.
																	<br>Variable debuffs were included as long as they had some real, numeric value at time of cast / play.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Buffs -->
										<div id="influenceBuffs" class="line_graph chart" alt="Stat-Buff Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceBuffsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceBuffsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all spells, units, and attachments.
																	<br>Debuffs must have been in one of four formats: +X/-X, +Armor, +Strength, or +Health.
																	<br>Variable buffs were included as long as they had some real, numeric value at time of cast / play.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>										
										
										<!-- Reactive -->
										<div id="influenceReactive" class="line_graph chart" alt="Reactive Card Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceReactiveInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceReactiveInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Reactive:
																	<br>	- Ambush
																	<br>	- Fast Spell
																	<br>
																	<br>All spells and units were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Card Cycling -->
										<div id="influenceCardCycling" class="line_graph chart" alt="Card Cycling Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceCyclingInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceCyclingInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Card Cycling:
																	<br>	- Draw
																	<br>	- Discard
																	<br>
																	<br>All spells and units were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Deck Manipulation -->
										<div id="influenceManipulation" class="line_graph chart" alt="Deck Manipulation Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceManipulationInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceManipulationInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Card types represented as Deck Manipulation:
																	<br>	- Search for and draw card
																	<br>	- Return card to influence
																	<br>	- Reorder influence
																	<br>	- Create cards & shuffle into deck
																	<br>	- Buffs applied to influence (in part or total)
																	<br>	- View top card
																	<br>	- Transform, silence, or slow cards in opponent influence
																	<br>	- Add cards to opponent influence
																	<br>	- Take cards from opponent influence
																	<br>	- All draw and discard effects
																	<br>
																	<br>All spells, units, and attachments were counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Units -->
										<div id="influenceUnits" class="line_graph chart" alt="Unit Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceUnitsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceUnitsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no influence not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Unit Offense -->
										<div id="influenceOffense" class="line_graph chart" alt="Unit Strength by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceOffenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceOffenseInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no influence not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
									<!-- Unit Defense -->
										<div id="influenceDefense" class="line_graph chart" alt="Unit Health by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceDefenseInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceDefenseInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Tokens and units with no influence not counted.
																	<br>Transmuted units counted.
																	<br>Spells producing units not counted.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Spells -->
										<div id="influenceSpells" class="line_graph chart" alt="Spell Availability by Influence"></div>	
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceSpellsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceSpellsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Units with Spell effects not included.
																	<br>Curses not included, as they are attachments.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										<!-- Curses -->
										<div id="influenceCurses" class="line_graph chart" alt="Curse Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceCursesInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceCursesInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Curses, but not Cursed Relics, included.
																	<br>Spells not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										<!-- Weapons -->
										<div id="influenceWeapons" class="line_graph chart" alt="Weapon Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceWeaponsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Only unit-based weapons included.
																	<br>Transmuted Monuments included.
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>Relic Weapons not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>																				
										<hr>
										
										<!-- Relic Weapons -->
										<div id="influenceRelicWeapons" class="line_graph chart" alt="Relic Weapon Availability by Influence"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceRelicWeaponsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceRelicWeaponsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>			

													
										<hr>
										
										<!-- Relics -->
										<div id="influenceRelics" class="line_graph chart" alt="Relic Availability by Influence"></div>	
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceRelicsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Relic Weapons not included.
																	<br>However, Relics generating armor or health are included. (e.g. Stronghold's Visage)
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Cursed Relics -->
										<div id="influenceCursedRelics" class="line_graph chart" alt="Cursed Relic Availability by Influence"></div>										
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceCursedRelicsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceCursedRelicsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Neither Relics nor Curses included, only Cursed Relics.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										
										<!-- Attachments -->
										<div id="influenceAttachments" class="line_graph chart" alt="Attachment Availability by Faction"></div>
													<br><div role="tablist" aria-multiselectable="true">
														<a data-toggle="collapse" href="#influenceAttachmentsInfo" aria-expanded="true">Data description<span class="glyphicon glyphicon-plus-sign"></span></a>
															<div id="influenceAttachmentsInfo" class="collapse" role="tabpanel">
																<BLOCKQUOTE>
																	<br>Includes all Curses, Cursed Relics, Relics, Relic Weapons, and Weapons.
																	<br>Spells producing weapons (e.g. Hone) not included.
																	<br>Transmuted Monuments included in count.
																	<br>
																	<br> Last update: August 23, 2017
																</BLOCKQUOTE>
															</div>
													</div>										
										<hr>
										<div id="" class="" alt=""></div>
									</div><!--close influence_container-->
								</div><!--close row-->
							</div><!--close influence-->
						</div><!--close pane-->
					</div><!--end tab-content-->
				</div><!--end container-2-->
			</div><!--end content-->
				
	<!--footer-->
			<?php include("./footer.html"); ?>
			

		</div><!--end container-1-->
	</body>

	<!--post-load scripts-->
			<!--js-->
			<script>
				$('.collapse').on('shown.bs.collapse', function(){
					$(this).parent().find(".glyphicon-plus").removeClass("glyphicon-plus").addClass("glyphicon-minus");
				}).on('hidden.bs.collapse', function(){
					$(this).parent().find(".glyphicon-minus").removeClass("glyphicon-minus").addClass("glyphicon-plus");
				});
			</script>
			
			<!--php-->
			<?php
				session_unset(); 
				session_destroy(); 
			?>
			
</div> <!--end page-->
</html>
